FROM ubuntu:18.04

RUN apt-get update;

## install git
RUN apt-get install git -y; 
#    git clone https://github.com/Duffney/becomeansible.git

#
#The following packages have unmet dependencies:
#git : Depends: perl but it is not going to be installed
#       Depends: liberror-perl but it is not going to be installed

